### ISSUE TITLE
Breaks custom gamma and fullscreen

### ISSUE THREAD

**Issue by andreasdc** [xCollateral/VulkanMod#111]
When I installed the newest update I had Minecraft in windowed mode and when I applied the changes my custom gamma (options.txt file) was resetted back to normal.

**Comment by xCollateral** [comment]
Did you change settings in game or did you edit `options.txt`?

**Comment by andreasdc** [comment]
Is it fixed?

**Comment by andreasdc** [comment]
bump

**Comment by Vcmp** [comment]
It looks like it might be a packaging issue as this problem occurs when using _./gradlew build_ to create the mod artifact from the 0.1.8 release [here](https://github.com/xCollateral/VulkanMod/releases/tag/0.1.8), however after testing it again with a mod artefact build with _./gradlew build_  with IntelliJ the issue disappears and does not overwrite the Options.txt file. 

The _./gradlew build_ version without IntelliJ also doesn't always apply the correct LWJGL version its supposed to (3.2.2 instead of 3.3.1) so it not just a Option.txt issue (Unless I built the mod Wrong)

**Comment by Vcmp** [comment]
I also notices that the runDiretctory variable used to load the options.txt file in MinecraftClient class is empty and doesn't point to the correct instance directory if run as a separate .jar mod, however in a Dev Environment it has the correct directory location so this is probably an easy mixin fix where the variable could be overridden manually with System.getProperty(user.dir). 

I might try to setup a small PR if that does fix it.

**Comment by Vcmp** [comment]
After testing this for a while I found that is is not a bug with vanilla/the Mod, it seems to be issue where the value must be formatted correctly to be read by the game, for gamma in options.txt 1-100 is in floating point format (0.0-1.0) so for value 45 it would be written as 0.45 and not 45 (in options.txt)

After doing that it seems to reflect the manually added value in the options menu and in game so it looks like when adding manual values to make sure that they are written absolutely correctly in the float format and not the int format.

**Comment by andreasdc** [comment]
I have gamma:100.0 in the options.txt and it works normally

**Comment by Vcmp** [comment]
Are manually added values to options.txt udpated and used properly in game or are they still being reset? (sorry if misunderstanding)

**Comment by andreasdc** [comment]
They are being resetted because VulkanMod sets it to max value of 1.0 if i'm not wrong.

**Comment by Vcmp** [comment]
I tried using a mod artefact via IntelliJ using the specific commit you mentioned https://github.com/xCollateral/VulkanMod/commit/b7e02eec4c19df4c535f83c0fe5f5029c3cc1143, and found that to set the gamma: correctly in options.txt the game must be closed, as if its changed in text editor by hand when the client is running it will override/reset it. 

I tried to set gamma:0.45 before launching the instance and it seems to set the brightness correctly at 45 in game, so unless I'm mistaken it has to be changed only when the client is not running.

**Comment by andreasdc** [comment]
Yes it must be closed. On this commit it works, on the newer with the options screen it doesn't work.

**Comment by andreasdc** [comment]
I think after you change something in the vulkanmod's settings it will reset gamma to max value which is 1.0.

**Comment by Vcmp** [comment]
Tried the following: (With the 0.1.8 1.18.2 version from curseforge with a developer version of PolyMC 5.0)
- let then client generate default options.txt, (e.g. deleting it or with fresh instance)
- changed gamma:1.0 to 0.125, (which rounds to 12) 
- launch the client, 
- change settings, (without touching the brightness slider in game), 
- close the client, 
- change a random option in options.txt ( e.g. fov:0.1 in options.txt to 0.200, )
- relaunch the client
- change random setting in game again

And gamma is still set to 0.125 instead of defaulting to 1.0 and brightness is set to 12 correctly and is not reset to 100/1.0 at any point, I did not touch the brightness slider at any point so unless I'm missing a s key step that triggers the bug to occur, I still can't seem to reproduce it at all. 

There likely is an actual issue/bug here that is happening, but I can't seem to create the right conditions to trigger it. (again apologies for being unhelpful)

**Comment by andreasdc** [comment]
1. I have gamma:100.0 in options.txt
2. I open VulkanMod's video settings.
3. I click apply.
4. Brightness is now changed.

**Comment by Vcmp** [comment]
I think I might understand the issue now, when set to 100.0 with the current blob https://github.com/xCollateral/VulkanMod/commit/1b04d8d00f9523254b7c5538feeadf9ce4b913ff the mod treats this as the equivalent of setting brightness level 10000, normally in vanilla I believe this is not clamped back to the default max of 1.0 (Brightness 100), however when the new options menu was added to this mod in options.java, if I'm not mistaken, default ranges are now enforced when they weren't before, so when it sees that gamma is above 1.0, it resets its back to the default range deliberately, so technically it is not a bug from a default settings perspective (and is arguably fixing a vanilla bug)

I tried removing the 100 limit on the 3rd parameter here to Integer.MAX_VALUE: https://github.com/xCollateral/VulkanMod/blob/1b04d8d00f9523254b7c5538feeadf9ce4b913ff/src/main/java/net/vulkanmod/config/Options.java#L68 and the gamma value at 100.0 was no longer reset back to 1.0 after changing and applying other settings and exiting and relaunching the game.

To allow the option.txt ranges you want to use, if i'm not wrong, the max limits need to be removed so it doesn't clamp the values back to the vanilla limits.

**Comment by Vcmp** [comment]
It looks like this when set in game if this is the correct behaviour

![2022-10-19_21 50 35](https://user-images.githubusercontent.com/43959737/196801955-fb7bbb52-a884-4017-907f-fd43e6cbaa2a.png)

**Comment by andreasdc** [comment]
if (gamma > normalMax) { 
dontsave
}
else {
save
}

**Comment by Vcmp** [comment]
I'm assuming you might have potentially meant trying to setup effects like this [AntVenom Video](https://www.youtube.com/watch?v=b64FiVAGU8w), (brightness/Gamma is also covered) in that case I will definitely think about looking into it as changing some of these parameters in game might be useful for some people as I was thinking of submitting a PR a bit similar to this anyway.

**Comment by andreasdc** [comment]
Still breaks gamma :/

**Comment by xCollateral** [comment]
I just retested it and it seems to be working properly. Gamma value ranges from 0.00 to 1.00 and it's correctly saved.
Are you applying changes before exiting menu? Can you test it on another launcher?

**Comment by andreasdc** [comment]
I changed in options file, like I described here:

> 1. I have gamma:100.0 in options.txt and latest VukanMod from actions [1b04d8d](https://github.com/xCollateral/VulkanMod/commit/1b04d8d00f9523254b7c5538feeadf9ce4b913ff)
> 2. I open VulkanMod's video settings.
> 3. I click apply.
> 4. Brightness is now changed to 1.0.

I guess it's not fixed yet and I can't use video settings in the game.

**Comment by Felix14-v2** [comment]
> I guess it's not fixed yet

This is a 1.19+ feature, Minecraft resets invalid values in options.txt, isn't it?
