### ISSUE TITLE
Screenshot missing Red from the color palette

### ISSUE THREAD

**Issue by nesuwu** [xCollateral/VulkanMod#190]
So, as the title of this issue says, its missing red
![2023-02-18_21 59 47](https://user-images.githubusercontent.com/103582424/219899670-e7498147-2091-42b6-997a-79f16da5c35e.png)
^
Screenshot Taken With Vulkan Renderer Mod Enabled
![2023-02-18_22 03 08](https://user-images.githubusercontent.com/103582424/219899666-7048e377-180e-4c58-ba4f-6ce95c7a85f5.png)
^
Screenshot Taken With Vulkan Renderer Mod Disabled

**Comment by thr3343** [comment]
This is a very old bug with the mod where the colour channels are not corrected properly when saving the image (GPU used BGR which causes the Red and Blue Channels to get incorrectly swapped before saving). This has been an issue for the longest time with the mod and it just didn't get fixed for some reason (likely due to being a more minor, non game-breaking bug).

There is a PR #186 I made a while ago that attempts to fix this and seems to work OK, however I haven't updated it for quite a long while and it contains some ugly code that hasn't been cleaned up so it may not work properly.

**Comment by thr3343** [comment]
~As a temporary workaround ImageViewers like IrfanView can be used to swap the R and B channels to fix the colours, which is what I currently use to handle VulkanMod Screenshots.~

**Comment by thr3343** [comment]
Just found out that this issue has been fixed upstream, (Which works much better than the PR I once made to fix this), so it shouldn't be a problem anymore.

**Comment by xCollateral** [comment]
It should be fixed now.
