### ISSUE TITLE
graphics glitch when custom font resource pack is applied

### ISSUE THREAD

**Issue by wb1016** [xCollateral/VulkanMod#199]
![image](https://user-images.githubusercontent.com/47267045/223479237-c80eedfe-80d8-4d3a-aa64-1df9181898ce.png)
how to reproduce: just apply any font resource pack

**Comment by pparaxan** [comment]
did the same but got this look
OS: Linux
I disabled all mods, only the Vulkan mod
Minecraft 1.19.2

![1](https://user-images.githubusercontent.com/111686716/224849623-63f8151f-dcaa-412e-bb7f-113a91ec91a3.png)

![2](https://user-images.githubusercontent.com/111686716/224849666-93fe2c7b-dbac-4063-bc7f-e84309684ad7.png)

![3](https://user-images.githubusercontent.com/111686716/224849688-d6aa7d58-58c5-485f-a561-dea8df0f9bf0.png)

**Comment by thr3343** [comment]
This bug is 100% confirmed, as I can reproduce this issue with ease using the [Roboto Bold](https://www.curseforge.com/minecraft/texture-packs/hd-font-roboto-bold) Font Pack as well: 
_(Using i7 4790K, GTX 1080Ti with Win10 21H1)_

I believe xCollateral is aware of this issue and will likely get fixed upstream once the 1.19.3/4 port is finished.

It seems to be worth noting that this only occurs with specific Packs as [Slightly Improved Font](https://www.curseforge.com/minecraft/texture-packs/slightly-improved-font) is fine.

![2023-03-14_21 17 39](https://user-images.githubusercontent.com/125277899/225138733-2c35ef7e-13fb-4c27-b17a-2a18a932c20b.png)

**Comment by nm17** [comment]
Also can reproduce this issue on my setup (GTX 1650, Linux Debian 12, Java 19, VulkanMod 0.2.5, MC 1.19.4).

Can't find anything related to this issue in the logs, but here they are (in case someone needs them): https://mclo.gs/TO5ltCd

**Comment by nm17** [comment]
This issue does not seem to be caused by a regression, since this bug is reproducible on all versions of VulkanMod since 0.1.5 on MC 1.18.2 (haven't tested any versions earlier than that)

**Comment by wb1016** [comment]
fixed in 0.3.0
