### ISSUE TITLE
Add link to vulcan hardware devices 

### ISSUE THREAD

**Issue by SrBedrock** [xCollateral/VulkanMod#250]
Add to the README the list of graphics cards compatible with Vulkan.

https://vulkan.gpuinfo.org/listdevices.php

**Comment by thr3343** [comment]
For the most part, the "min Requirements" so to speak is any GPU that supports Vulkan 1.2 or later, which is usually anything that isn't garbage tier drivers (i.e. alot of Android Devices are still stuck on 1.1), and anything from 2013 onwards iirc.

Initially, 0.3.0 required a min of Vulkan 1.3, but alot of ppl had major issues with handling it, so it was dropped to 1.2 + Dynamic Rendering, which has a much better level of support afaik.

OTOH, we massively underestimated how truely/actually bad the inconsitency of driver support with Dynamic Rendering was/is, and there is major issues with some ppl lacking Dynamic Rendering support due to old/outdated/buggy drivers, either due to running very old <2013 GPUs and/or running some specific intel iGPUs.

About 99% of these cases are directly caused by being dropped from driver support recently, which is what has happend to some Intel iGPUs from September 2022.

**Comment by thr3343** [comment]
OTOH if its possible/a good idea to remove Dynamic Rendering without causing massive code breaking changes/other issues, hopefully the requirements can be relaxed alot so only anything with barebones 1.2 support is needed; and therefore a more comprehsive list may not be 100% needed
