### ISSUE TITLE
Problems with textures on mod version 0.3.3

### ISSUE THREAD

**Issue by dcmen007** [xCollateral/VulkanMod#308]
I put a mod on the Vulkan API version 0.3.3 on Minecraft 1.20.2 and the textures of the chests, the bed and the enchantment table began to glitch
![2023-09-24_10 41 08](https://github.com/xCollateral/VulkanMod/assets/137626367/bceffc12-8872-4bc0-a061-d25989d3a678)
![2023-09-24_10 41 16](https://github.com/xCollateral/VulkanMod/assets/137626367/d8f42344-65ee-4345-9464-465a3c6cdfd5)

**Comment by MrWyder** [comment]
I also have the same problem with this thing. Without VulkanMod or just Fabric it's fine, but with Vulkan this happens in the same version 0.3.3 in Minecraft version 1.20.2. 
The same thing happens on beds (any colour), chests (all three versions), shulker boxes (any colour), shields, banners (any pattern or colour) and the Enchantment Table. Please fix this because it's very weird!
![2023-09-24_18 47 58](https://github.com/xCollateral/VulkanMod/assets/145926656/505f51b6-b148-49f1-8b01-28d799abe7af)
And sorry for the weird picture but it looks the same from any angle based on this post.

**Comment by AdoLovesChicken** [comment]
I also have this issue, with signs, enchantment tables (the book), chests and beds. These textures do not look like the other errors in this issue but are still glitched.
![2023-12-02_10 30 42](https://github.com/xCollateral/VulkanMod/assets/119848686/7c1f3502-c7d7-4c0d-8371-e108805ccc15)

And here are all three chests.
![2023-12-02_10 33 38](https://github.com/xCollateral/VulkanMod/assets/119848686/cd3a4d79-edd2-4b95-8efa-ecfc3c44e03a)

VulkanMod 0.3.6 for 1.20.1
Please fix soon.
