### ISSUE TITLE
Weird sounds

### ISSUE THREAD

**Issue by andreasdc** [xCollateral/VulkanMod#34]
Sound are played differently or at a different volume, when compared to setup with Sodium for example.

**Comment by Zorklis** [comment]
Any news on this? Did you try to update vulkan to latest?

**Comment by andreasdc** [comment]
I will try when VulkanMod will be better than Sodium again.

**Comment by Zorklis** [comment]
Oh perfect so you can try it out. This should be closed

**Comment by andreasdc** [comment]
Sure you can tag me when the performance will be better than on Sodium, it was like that on 1.17.

**Comment by Zorklis** [comment]
32 Chunks, no stutters with Vulkan. Sodium is stutter town. Anyways performance is not the issue you listed. This should be closed.

**Comment by thr3343** [comment]
> Sure you can tag me when the performance will be better than on Sodium, it was like that on 1.17.

Which version performs the best for you currently? 
i'm assuming everything from 0.15 onwards is slower, 
(As [0.1.4 build 3](https://github.com/xCollateral/VulkanMod/releases/tag/0.1.4%2B), as that is the last version released for 1.17 afaik)

If I know which version, i might be able to track the regression down and restore the lost FPS

Outside of that, TBH alot of this is probably due to 1.18+ effecting performance rather than VulkanMod itself; 
As not everything is within our control due to Mojang changes(i.e. 1.20+  uses more memory + has GC spikes)

If you need more help, I would suggest opening a separate issue about this entirely
_(e.g. 1.17 versions performed better than 1.18+)_

Or alternatively Joining the Discord if you want (we have a #support channel)

**Comment by thr3343** [comment]
> 32 Chunks, no stutters with Vulkan. Sodium is stutter town. Anyways performance is not the issue you listed. This should be closed.

I will let Collateral know about this, so this gets closed
TBH we've been very busy with testing + development recently, so we forgot to cleanup and close alot of outdated issues on the repo.

**Comment by andreasdc** [comment]
1.20 performs better for me than 1.19. Last time even Exordium or ImmediatelyFast were not working.
