### ISSUE TITLE
Linux Arm support required

### ISSUE THREAD

**Issue by Llerey** [xCollateral/VulkanMod#439]
Launchers for running Minecraft Java are actively being developed on mobile devices.
Mobile devices support Vulcan, but they don't support openGL.
It would be nice to add support for Linux Arm 32 and Arm 64 to this modification
To be able to run on Android 12+ devices
Android 9+ has support for Vulcan 1.1, android 13 has support for Vulcan 1.3

Mobile Launchers Mentioned:
https://github.com/PojavLauncherTeam/FFmpegPlugin
https://github.com/FCL-Team/FoldCraftLauncher

**Comment by Felix14-v2** [comment]
Android "ipad kids" is exactly the reason why VulkanMod doesn't support ARM devices at all. There was an experimental unofficial support in the past, but mobile users turned out to be too problematic. Especially the YouTube community. It's just not worth anyone's effort. VulkanMod has many other priorities (like shader support ~and removing Herobrine~) that are more important for now.

**Comment by ShadowMC69** [comment]
> Android "ipad kids" is exactly the reason why VulkanMod doesn't support ARM devices at all. There was an experimental unofficial support in the past, but mobile users turned out to be too problematic. Especially the YouTube community. It's just not worth anyone's effort. VulkanMod has many other priorities (like shader support ~and removing Herobrine~) that are more important for now.

Fr

**Comment by AwesomeCoder412412** [comment]
For those of us who are running Minecraft on ARM64 Linux computers, it would be very nice if we could get Vulkan support. Considering that Minecraft already runs fantastic on ARM Linux, how much additional work would need to be done to achieve this?

**Comment by thr3343** [comment]
> For those of us who are running Minecraft on ARM64 Linux computers, it would be very nice if we could get Vulkan support. Considering that Minecraft already runs fantastic on ARM Linux, how much additional work would need to be done to achieve this?

Adding ARM support for Linux is extremely trivial.
The real problem is if the Linux ARM devices in question have VK1.2 support

Afaik some Chromebooks use Mali tilers _(tilers are basically mobile GPUs)_ which tend to be ng as they sometimes have outdated VK1.1 drivers

As long as its VK1.2 and not ARM32, that it should be fine on VulkanMod

**Comment by thr3343** [comment]
> Android "ipad kids" is exactly the reason why VulkanMod doesn't support ARM devices at all. There was an experimental unofficial support in the past, but mobile users turned out to be too problematic. Especially the YouTube community. It's just not worth anyone's effort. VulkanMod has many other priorities (like shader support ~and removing Herobrine~) that are more important for now.

This isn't actually the case: Android compat needs [VK_KHR_android_surface](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_android_surface.html) to create an app window, and GLFW doesn't support Android at all.

As a result we can add ARM64 platforms, without adding Android support at the same time 
_(tl;dr: ARM compat is very werid in general)_

**Comment by Inverted-Fin** [comment]
> 对于我们这些在 ARM64 Linux 计算机上运行 Minecraft 的人来说，如果我们能获得 Vulkan 支持，那就太好了。考虑到Minecraft已经在ARM Linux上运行得非常出色，还需要做多少额外的工作才能实现这一目标？

Yes,its original supports make our devices can get higer fps,it seem very good now

**Comment by JimBimBum** [comment]
just converting gl 3.2 to gles 3 sounds simpler than rewriting the mod for arm support since gl and gles are far similiar than x86_64 & Arm. as for Arm linux, there's no way to translate x86_64 to arm? there's a way to translate arm to x86_64 so it should be possible to do the reverse. most of the issues here seem like it can be solved by the community as translation layers becoming far more popular.

**Comment by AwesomeCoder412412** [comment]
> just converting gl 3.2 to gles 3 sounds simpler than rewriting the mod for arm support since gl and gles are far similiar than x86_64 & Arm. as for Arm linux, there's no way to translate x86_64 to arm? there's a way to translate arm to x86_64 so it should be possible to do the reverse. most of the issues here seem like it can be solved by the community as translation layers becoming far more popular.

??????????

I admit that I don't have a great understand of the internals of this mod, but I do understand how Java and cross-platform APIs work. This mod is not written for x86_64, and it's not written for ARM. Java code is written to compile to Java bytecode, which runs in the JVM, which runs on most of the computer architectures I can imagine, including ARM. Minecraft works natively on ARM machines because of this. The vast majority of mods work perfectly on my ARM64 Linux machine because of this.

Different Graphics APIs are also entirely separate from different CPU architectures, and comparing between them is completely nonsensical. They are in entirely different leagues.

Why would we convert OpenGl to GLES 3? First of all, that isn't even necessary, as OpenGL 4.6 is fully supported by most ARM Linux Desktop systems (which is what we're talking about right now, as above it has been established that android/mobile device support is out of the question), including mine.

In fact, there's probably a very good chance this mod works perfectly fine on a ARM Linux system with Vulkan support, but I'm still waiting for proper Vulkan support to come to my ARM Linux distribution and wanted to see if it was supported in the meantime. If there is any porting to be done, I couldn't imagine it taking more than a few hours of work (I am technically guessing on this front, though. If any developers of this mod wish to correct me, please go ahead.)

**Comment by Felix14-v2** [comment]
> there is any porting to be done, I couldn't imagine it taking more than a few hours of work

Actually there are forks with ARM support, so you can try it yourself

**Comment by Inverted-Fin** [comment]
As you see,this mod get 120fps or higher on my device,this is choice truly,we maybe need original performance likes vulkan render with no openGL support(such as Adreno,Mali GPU))

![1000129459.jpg](https://github.com/user-attachments/assets/caf1ae3b-9cda-4d30-9c85-89f5af07946b)

![1000129458.jpg](https://github.com/user-attachments/assets/bfdfe893-5fa9-4990-8cbd-e1b485f2693d)

**Comment by AwesomeCoder412412** [comment]
> > there is any porting to be done, I couldn't imagine it taking more than a few hours of work
> 
> 
> 
> Actually there are forks with ARM support, so you can try it yourself

That's great! Could you point me in the direction of some of these forks?

**Comment by AwesomeCoder412412** [comment]
> As you see,this mod get 120fps or higher on my device,this is choice truly,we maybe need original performance likes vulkan render with no openGL support(such as Adreno,Mali GPU))
> 
> ![1000129459.jpg](https://github.com/user-attachments/assets/caf1ae3b-9cda-4d30-9c85-89f5af07946b)
> 
> ![1000129458.jpg](https://github.com/user-attachments/assets/bfdfe893-5fa9-4990-8cbd-e1b485f2693d)
> 
> 

Are you using a fork with ARM support here, or were you able to just use unmodified VulkanMod?

**Comment by whitebelyash** [comment]
> For those of us who are running Minecraft on ARM64 Linux computers, it would be very nice if we could get Vulkan support. Considering that Minecraft already runs fantastic on ARM Linux, how much additional work would need to be done to achieve this?

Unmodified VulkanMod already runs fine on ARM64 desktop Linux (even on Asahi with unusual page size). 
It isn't working out of the box, but adding required arm64 libs in the librarypath is trivial.
![Screenshot from 2024-08-04 09-39-23](https://github.com/user-attachments/assets/0e9c288a-fe1d-4f5d-bf5d-b70cbe516155)

**Comment by Inverted-Fin** [comment]
> > As you see,this mod get 120fps or higher on my device,this is choice truly,we maybe need original performance likes vulkan render with no openGL support(such as Adreno,Mali GPU))
> > 
> > ![1000129459.jpg](https://github.com/user-attachments/assets/caf1ae3b-9cda-4d30-9c85-89f5af07946b)
> > 
> > ![1000129458.jpg](https://github.com/user-attachments/assets/bfdfe893-5fa9-4990-8cbd-e1b485f2693d)
> > 
> > 
> 
> Are you using a fork with ARM support here, or were you able to just use unmodified VulkanMod?

Yes,it 's a fork with arm linux support,a unofficial patch(in vulkan mod discord).

**Comment by xCollateral** [comment]
Android modified libs are available at [Curseforge](https://www.curseforge.com/minecraft/mc-mods/vulkanmod-android-libs), but please keep in mind we offer no support to Android/Pojav users.
